# Site Configuration
# Update these values for each new project

site:
  title: "William Hou - Portfolio"
  description: "William Hou's Portfolio"
  author: "williamhCode"
  url: "https://williamhcode.github.io"
  keywords:
    - Portfolio

# Social Media / Open Graph
social:
  ogImage: "/assets/me.webp"
